name: release-npm

on:
  push:
    branches:
      - main

permissions:
  id-token: write # OIDC
  contents: write # release-please (create commit)
  pull-requests: write # release-please (create PR)

jobs:
  release-please:
    runs-on: ubuntu-latest
    environment: release-npm
    concurrency: release-npm

    steps:
      # these two are required:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 26

      # run any prerequisite steps to generate the publishable output
      # no need for lint/test, since they run in your main CI workflow. just build.
      - run: npm ci
      - run: npm run typecheck

      - uses: k-yle/npm-publish@c56a772f8626c8feeabb26d5e0d129a145f56975
        id: publish
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
